### ISSUE TITLE
[ePI] Adapt connector to retrieve resources from IG

### ISSUE THREAD

**Issue by gmej** [Gravitate-Health/fhir-connector#15]

**Comment by gmej** [comment]
https://build.fhir.org/ig/joofio/test-epi-composition/toc.html

**Comment by gmej** [comment]
@joofio I have a question, is there an endpoint in the previous link that gives all the bundles or references to them in order to retrieve them from FOSPS so they are available for us?

**Comment by gmej** [comment]
OR are those bundles uploaded anywhere?

**Comment by joofio** [comment]
http://sandbox.hl7europe.eu/gravitate/fhir/Bundle

**Comment by gmej** [comment]
thanks

**Comment by gmej** [comment]
@joofio you have a problem with your HAPI FHIR deployment. Pagination is broken.

When requesting a GET to /bundle, the "next" page is missing part of the path.
The next url is constructed like this (missing "/fhir/" in path): 
```
http://sandbox.hl7europe.eu/gravitate?_getpages=fc1cc8c0-39a2-4d3b-b59e-6b90b3ad7e30&_getpagesoffset=10&_count=10&_pretty=true&_bundletype=searchset
```
When it should be like (with "/fhir" in path):

```
http://sandbox.hl7europe.eu/gravitate/fhir?_getpages=fc1cc8c0-39a2-4d3b-b59e-6b90b3ad7e30&_getpagesoffset=10&_count=10&_pretty=true&_bundletype=searchset
```

I think you are missing the "SERVER_SERVLET_CONTEXT_PATH" environment variable to configure the deployment of HAPI FHIR server under a different path. 

Please tell me when it is solved so I can execute the connector (it is ready but waiting for the pagination to work)

![image](https://github.com/Gravitate-Health/fhir-connector/assets/48624760/aeec6545-8926-4428-9a66-9fa377851ac1)

**Comment by joofio** [comment]
Why do you need that for the review ?

**Comment by gmej** [comment]
Alejandro commented us that you wanted those ePIs to be shown in the review

**Comment by joofio** [comment]
There is no need for that. The need for the epis is the ig which is done.
However, this should be done of course.

**Comment by gmej** [comment]
OK then. I'll do it but not necessary for the review ok. Anyway for us to develop this connector we should solve this issue, not urgent as you say.

**Comment by joofio** [comment]
by the looks of it, it seems like a bug. but more analysis is required

**Comment by jkiddo** [comment]
<img width="1002" alt="image" src="https://github.com/Gravitate-Health/fhir-connector/assets/211696/fc180f4b-c6bd-494f-8e5f-f31742873e77">

**Comment by jkiddo** [comment]
seems to work fine to me

**Comment by gmej** [comment]
then it might not be a bug but a misconfiguration?

**Comment by jkiddo** [comment]
```
server:
  port : 8080
  servlet:
    context-path: /example/path
```

**Comment by joofio** [comment]
should be solved

**Comment by gmej** [comment]
URL changed to [http://sandbox.hl7europe.eu/gravitate-health/fhir/](http://sandbox.hl7europe.eu/gravitate-health/fhir/)

**Comment by joofio** [comment]
@gmej to test and close if done

**Comment by gmej** [comment]
@joofio I was about to finish this task, but the server looks like it has no ePIs.
https://sandbox.hl7europe.eu/gravitate-health/fhir/Bundle returns 0 results.

**Comment by joofio** [comment]
check now

**Comment by gmej** [comment]
Done. Now we have 1290 ePIs in dev.

Close this issue when you want. Next step we will generate provenance for all of them in #17
