### ISSUE TITLE
Create API for connector to run connectors on demand.

### ISSUE THREAD

**Issue by gmej** [Gravitate-Health/fhir-connector#18]

**Comment by gmej** [comment]
New feature available: running connectors on demand via the connector API. @joofio you are going to like this very much.

Check the API definition here: https://gravitate-health.lst.tfo.upm.es/swagger-fosps/?urls.primaryName=FHIR%20Connector#/


List available connectors:
```bash
curl --location 'https://gravitate-health.lst.tfo.upm.es/connector/api/connectors/list'
```
Run a connector:
```bash
curl --location --request POST 'https://gravitate-health.lst.tfo.upm.es/connector/api/connectors/fhir-connector-git-ips/run'
```

Like lenses and preprocessors, FOSPS now automatically discovers future deployments of new connectors.

**Comment by gmej** [comment]
We can close this as completed, it's already implemented.

**Comment by gmej** [comment]
I have protected both  `/connector/api/connectors/list` and `/api/connectors/CONNECTOR_NAME/run` endpoints with authentication, to avoid strange things, as those endpoints execute services in the backend.

**Comment by joofio** [comment]
how can i test?

**Comment by gmej** [comment]
> New feature available: running connectors on demand via the connector API. @joofio you are going to like this very much.
> 
> Check the API definition here: https://gravitate-health.lst.tfo.upm.es/swagger-fosps/?urls.primaryName=FHIR%20Connector#/
> 
> List available connectors:
> 
> ```shell
> curl --location 'https://gravitate-health.lst.tfo.upm.es/connector/api/connectors/list'
> ```
> 
> Run a connector:
> 
> ```shell
> curl --location --request POST 'https://gravitate-health.lst.tfo.upm.es/connector/api/connectors/fhir-connector-git-ips/run'
> ```
> 
> Like lenses and preprocessors, FOSPS now automatically discovers future deployments of new connectors.

Look this. We have three connectors availables for now, named:
- "fhir-connector-git-ips" (git repo)
- "fhir-connector-fhir-sync-hl7" (ema ePIs)
- "fhir-connector-git-epi" (git repo)
Remember it requieres a valid JWT in the Authorization header.

**Comment by joofio** [comment]
Tested and seems ok! Great
