### ISSUE TITLE
Cronjob execution of the connector does not end

### ISSUE THREAD

**Issue by gmej** [Gravitate-Health/fhir-connector#3]
Execution is OK, but never ends, and the pods keeps running.

**Comment by gmej** [comment]
As the first comment of this [stackoverflow post](https://stackoverflow.com/questions/56485280/kubernetes-jobs-not-completing) says, it looks like a istio Bug: https://github.com/istio/istio/issues/6324

**Comment by 10alejospain** [comment]
Maybe not inyecting the istio sidecart to the cron?

**Comment by gmej** [comment]
I didn't quite understand as further research is needed, but it was definetely something related to Istio sidecars. We'll have to look for a workaround if this is not fixed yet (as I didn't see that it was fixed yet)

**Comment by gmej** [comment]
Looks like this commit fixed the problem https://github.com/Gravitate-Health/fhir-connector/commit/a282d573e718e41370b7fb03e19a2d8eb721c9d2. Closing issue
